package agg.agg;


import anywheresoftware.b4a.BA;
import anywheresoftware.b4a.BALayout;
import anywheresoftware.b4a.debug.*;

public class uisizes {
private static uisizes mostCurrent = new uisizes();
public static Object getObject() {
    throw new RuntimeException("Code module does not support this method.");
}
 public anywheresoftware.b4a.keywords.Common __c = null;
public static int _defaultpadding = 0;
public static int _chartdefaultheight = 0;
public static int _objectsstartingleft = 0;
public static int _objectsstartingtop = 0;
public static int _objectsdefaultbuttonheight = 0;
public static int _objectsdefaultlabelheight = 0;
public static int _objectvseperation = 0;
public static int _scrollbottompadding = 0;
public static int _defaulttextsize = 0;
public static int _defaultbuttonwidth = 0;
public static int _defaulteditwidth = 0;
public static int _defaultlabelwidth = 0;
public static int _quickchartleft = 0;
public static int _quickchartleftoriginal = 0;
public static int _labeleditspacing = 0;
public static int _defaulttitlesize = 0;
public static int _defaultbuttontextsize = 0;
public static int _defaultbigtitlesize = 0;
public static int _defaultcharttextsize = 0;
public static int _defaulterrmsgsize = 0;
public static int _mainheaderheight = 0;
public static int _mainheaderheightlandscape = 0;
public static int _imagepadding = 0;
public static int _tableheaderheight = 0;
public static int _defaultcontrolheight = 0;
public static int _floatingbuttonsize = 0;
public static int _smallfloatingbuttonsize = 0;
public static int _floatinganimspeed = 0;
public static int _slidemenuwidth = 0;
public anywheresoftware.b4a.samples.httputils2.httputils2service _httputils2service = null;
public agg.agg.main _main = null;
public agg.agg.helperfunctions _helperfunctions = null;
public agg.agg.programdata _programdata = null;
public agg.agg.version _version = null;
public static String  _initialize(anywheresoftware.b4a.BA _ba) throws Exception{
 //BA.debugLineNum = 28;BA.debugLine="Public Sub Initialize";
 //BA.debugLineNum = 30;BA.debugLine="DefaultPadding = 1%x";
_defaultpadding = anywheresoftware.b4a.keywords.Common.PerXToCurrent((float) (1),_ba);
 //BA.debugLineNum = 32;BA.debugLine="ObjectsStartingLeft = 2%x			'Default 2%x, where t";
_objectsstartingleft = anywheresoftware.b4a.keywords.Common.PerXToCurrent((float) (2),_ba);
 //BA.debugLineNum = 33;BA.debugLine="ObjectsDefaultButtonHeight = 42dip	'Default 42dip";
_objectsdefaultbuttonheight = anywheresoftware.b4a.keywords.Common.DipToCurrent((int) (42));
 //BA.debugLineNum = 34;BA.debugLine="ObjectsDefaultLabelHeight  = 32dip	'Default 48dip";
_objectsdefaultlabelheight = anywheresoftware.b4a.keywords.Common.DipToCurrent((int) (32));
 //BA.debugLineNum = 35;BA.debugLine="ChartDefaultHeight = 77%y";
_chartdefaultheight = anywheresoftware.b4a.keywords.Common.PerYToCurrent((float) (77),_ba);
 //BA.debugLineNum = 36;BA.debugLine="ObjectVSeperation = 0.5%y";
_objectvseperation = anywheresoftware.b4a.keywords.Common.PerYToCurrent((float) (0.5),_ba);
 //BA.debugLineNum = 37;BA.debugLine="SlideMenuWidth = 164dip";
_slidemenuwidth = anywheresoftware.b4a.keywords.Common.DipToCurrent((int) (164));
 //BA.debugLineNum = 38;BA.debugLine="DefaultButtonWidth = 22%x";
_defaultbuttonwidth = anywheresoftware.b4a.keywords.Common.PerXToCurrent((float) (22),_ba);
 //BA.debugLineNum = 39;BA.debugLine="DefaultEditWidth = 40%x";
_defaulteditwidth = anywheresoftware.b4a.keywords.Common.PerXToCurrent((float) (40),_ba);
 //BA.debugLineNum = 40;BA.debugLine="DefaultLabelWidth = 108dip";
_defaultlabelwidth = anywheresoftware.b4a.keywords.Common.DipToCurrent((int) (108));
 //BA.debugLineNum = 41;BA.debugLine="QuickChartLeft = 36%x";
_quickchartleft = anywheresoftware.b4a.keywords.Common.PerXToCurrent((float) (36),_ba);
 //BA.debugLineNum = 42;BA.debugLine="QuickChartLeftOriginal = 36%x";
_quickchartleftoriginal = anywheresoftware.b4a.keywords.Common.PerXToCurrent((float) (36),_ba);
 //BA.debugLineNum = 43;BA.debugLine="LabelEditSpacing = 6dip";
_labeleditspacing = anywheresoftware.b4a.keywords.Common.DipToCurrent((int) (6));
 //BA.debugLineNum = 46;BA.debugLine="DefaultTextSize = 12 'Default 12";
_defaulttextsize = (int) (12);
 //BA.debugLineNum = 47;BA.debugLine="DefaultErrMsgSize = 16	'Default 16";
_defaulterrmsgsize = (int) (16);
 //BA.debugLineNum = 48;BA.debugLine="RecalculateSizes";
_recalculatesizes(_ba);
 //BA.debugLineNum = 50;BA.debugLine="MainHeaderHeight =  42dip 'Default 52dip, 42dip -";
_mainheaderheight = anywheresoftware.b4a.keywords.Common.DipToCurrent((int) (42));
 //BA.debugLineNum = 51;BA.debugLine="MainHeaderHeightLandscape =  42dip 'Default 52dip";
_mainheaderheightlandscape = anywheresoftware.b4a.keywords.Common.DipToCurrent((int) (42));
 //BA.debugLineNum = 52;BA.debugLine="ObjectsStartingTop = 8dip";
_objectsstartingtop = anywheresoftware.b4a.keywords.Common.DipToCurrent((int) (8));
 //BA.debugLineNum = 53;BA.debugLine="imagePadding = 8dip";
_imagepadding = anywheresoftware.b4a.keywords.Common.DipToCurrent((int) (8));
 //BA.debugLineNum = 54;BA.debugLine="TableHeaderHeight = 48dip";
_tableheaderheight = anywheresoftware.b4a.keywords.Common.DipToCurrent((int) (48));
 //BA.debugLineNum = 55;BA.debugLine="DefaultControlHeight = DipToCurrent(24 + DefaultT";
_defaultcontrolheight = anywheresoftware.b4a.keywords.Common.DipToCurrent((int) (24+_defaulttextsize));
 //BA.debugLineNum = 56;BA.debugLine="DefaultLabelWidth = DipToCurrent(108 + DefaultTex";
_defaultlabelwidth = anywheresoftware.b4a.keywords.Common.DipToCurrent((int) (108+_defaulttextsize));
 //BA.debugLineNum = 57;BA.debugLine="SmallFloatingButtonSize = 50dip";
_smallfloatingbuttonsize = anywheresoftware.b4a.keywords.Common.DipToCurrent((int) (50));
 //BA.debugLineNum = 58;BA.debugLine="FloatingAnimSpeed = 110";
_floatinganimspeed = (int) (110);
 //BA.debugLineNum = 59;BA.debugLine="End Sub";
return "";
}
public static String  _process_globals() throws Exception{
 //BA.debugLineNum = 2;BA.debugLine="Private Sub Process_Globals";
 //BA.debugLineNum = 4;BA.debugLine="Public DefaultPadding As Int";
_defaultpadding = 0;
 //BA.debugLineNum = 5;BA.debugLine="Public ChartDefaultHeight As Int";
_chartdefaultheight = 0;
 //BA.debugLineNum = 6;BA.debugLine="Public ObjectsStartingLeft As Int";
_objectsstartingleft = 0;
 //BA.debugLineNum = 7;BA.debugLine="Public ObjectsStartingTop As Int";
_objectsstartingtop = 0;
 //BA.debugLineNum = 8;BA.debugLine="Public ObjectsDefaultButtonHeight As Int";
_objectsdefaultbuttonheight = 0;
 //BA.debugLineNum = 9;BA.debugLine="Public ObjectsDefaultLabelHeight As Int";
_objectsdefaultlabelheight = 0;
 //BA.debugLineNum = 10;BA.debugLine="Public ObjectVSeperation As Int";
_objectvseperation = 0;
 //BA.debugLineNum = 11;BA.debugLine="Public SCrollBottomPadding As Int = 2dip 'Ignore.";
_scrollbottompadding = anywheresoftware.b4a.keywords.Common.DipToCurrent((int) (2));
 //BA.debugLineNum = 12;BA.debugLine="Public DefaultTextSize As Int";
_defaulttextsize = 0;
 //BA.debugLineNum = 13;BA.debugLine="Public DefaultButtonWidth, DefaultEditWidth, Defa";
_defaultbuttonwidth = 0;
_defaulteditwidth = 0;
_defaultlabelwidth = 0;
 //BA.debugLineNum = 14;BA.debugLine="Public QuickChartLeft, QuickChartLeftOriginal As";
_quickchartleft = 0;
_quickchartleftoriginal = 0;
 //BA.debugLineNum = 15;BA.debugLine="Public LabelEditSpacing As Int";
_labeleditspacing = 0;
 //BA.debugLineNum = 16;BA.debugLine="Public DefaultTitleSize, DefaultButtonTextSize, D";
_defaulttitlesize = 0;
_defaultbuttontextsize = 0;
_defaultbigtitlesize = 0;
_defaultcharttextsize = 0;
_defaulterrmsgsize = 0;
 //BA.debugLineNum = 17;BA.debugLine="Public MainHeaderHeight, MainHeaderHeightLandscap";
_mainheaderheight = 0;
_mainheaderheightlandscape = 0;
 //BA.debugLineNum = 18;BA.debugLine="Public imagePadding As Int";
_imagepadding = 0;
 //BA.debugLineNum = 19;BA.debugLine="Public TableHeaderHeight As Int";
_tableheaderheight = 0;
 //BA.debugLineNum = 20;BA.debugLine="Public DefaultControlHeight As Int";
_defaultcontrolheight = 0;
 //BA.debugLineNum = 21;BA.debugLine="Public FloatingButtonSize, SmallFloatingButtonSiz";
_floatingbuttonsize = 0;
_smallfloatingbuttonsize = 0;
 //BA.debugLineNum = 22;BA.debugLine="Public FloatingAnimSpeed As Int";
_floatinganimspeed = 0;
 //BA.debugLineNum = 23;BA.debugLine="Public SlideMenuWidth As Int";
_slidemenuwidth = 0;
 //BA.debugLineNum = 25;BA.debugLine="End Sub";
return "";
}
public static String  _recalculatesizes(anywheresoftware.b4a.BA _ba) throws Exception{
 //BA.debugLineNum = 62;BA.debugLine="Public Sub RecalculateSizes";
 //BA.debugLineNum = 63;BA.debugLine="DefaultBigTitleSize = DefaultTextSize + 6";
_defaultbigtitlesize = (int) (_defaulttextsize+6);
 //BA.debugLineNum = 64;BA.debugLine="DefaultTitleSize = DefaultTextSize + 2";
_defaulttitlesize = (int) (_defaulttextsize+2);
 //BA.debugLineNum = 65;BA.debugLine="DefaultButtonTextSize = DefaultTextSize";
_defaultbuttontextsize = _defaulttextsize;
 //BA.debugLineNum = 66;BA.debugLine="DefaultChartTextSize = DefaultTextSize - 2";
_defaultcharttextsize = (int) (_defaulttextsize-2);
 //BA.debugLineNum = 67;BA.debugLine="DefaultErrMsgSize = DefaultTextSize + 2";
_defaulterrmsgsize = (int) (_defaulttextsize+2);
 //BA.debugLineNum = 68;BA.debugLine="End Sub";
return "";
}
}
